### ISSUE TITLE
Test File Failed

### ISSUE THREAD

**Issue by triplexacies** [tadatitam/info-flow-experiments#10]
Depending on the example file running(gender, msn respectively) I get either of the two errors:

WebDriverException: Message: Can't load the profile. Profile Dir: %s If you specified a log_file in the FirefoxBinary constructor, check it for details.

Ran 1 test in 30.490sRan 1 test in 30.492s

FAILEDFAILED (errors=1) (errors=1)
Instance 0 exiting!

Instance 1 exiting!
Experiment Complete
Traceback (most recent call last):
  File "test.msn.py", line 55, in <module>
    treatment_names=["control (auto)", "experimental (auto)"])
  File "../core/adfisher.py", line 76, in do_experiment
    if(len(result)==3):
TypeError: object of type 'bool' has no len()

**Comment by tadatitam** [comment]
Hi Mark, could you please try the demo_exp and let me know if that works?

**Comment by triplexacies** [comment]
python demo_exp.py
Beginning Collection
E
======================================================================
ERROR: runTest (web.pre_experiment.alexa.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../core/web/pre_experiment/alexa.py", line 17, in setUp
    self.unit = make_browser(-1, -1)
  File "demo_exp.py", line 14, in make_browser
    treatment_id=treatment_id, headless=False, proxy = None)
  File "../core/web/google_news.py", line 32, in __init__
    google_ads.GoogleAdsUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/google_ads.py", line 31, in __init__
    google_search.GoogleSearchUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/google_search.py", line 37, in __init__
    browser_unit.BrowserUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/browser_unit.py", line 40, in __init__
    self.driver = webdriver.Firefox(proxy=sproxy)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.


----------------------------------------------------------------------
Ran 1 test in 1.109s

FAILED (errors=1)
Collection Complete. Results stored in  demo.txt
Starting Experiment
Block  1
E
E
======================================================================
ERROR: runTest (adfisher.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../core/adfisher.py", line 47, in setUp
    self.unit = make_unit(unit_id, treatment_id)
  File "demo_exp.py", line 14, in make_browser
    treatment_id=treatment_id, headless=False, proxy = None)
  File "../core/web/google_news.py", line 32, in __init__
    google_ads.GoogleAdsUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/google_ads.py", line 31, in __init__
    google_search.GoogleSearchUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/google_search.py", line 37, in __init__
    browser_unit.BrowserUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/browser_unit.py", line 40, in __init__
    self.driver = webdriver.Firefox(proxy=sproxy)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.


----------------------------------------------------------------------
Ran 1 test in 1.140s

FAILED (errors=1)
Instance 0 exiting!
======================================================================
ERROR: runTest (adfisher.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../core/adfisher.py", line 47, in setUp
    self.unit = make_unit(unit_id, treatment_id)
  File "demo_exp.py", line 14, in make_browser
    treatment_id=treatment_id, headless=False, proxy = None)
  File "../core/web/google_news.py", line 32, in __init__
    google_ads.GoogleAdsUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/google_ads.py", line 31, in __init__
    google_search.GoogleSearchUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/google_search.py", line 37, in __init__
    browser_unit.BrowserUnit.__init__(self, browser, log_file, unit_id, treatment_id, headless, proxy=proxy)
  File "../core/web/browser_unit.py", line 40, in __init__
    self.driver = webdriver.Firefox(proxy=sproxy)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 77, in __init__
    self.binary, timeout),
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 49, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.


----------------------------------------------------------------------
Ran 1 test in 1.135s

FAILED (errors=1)
Instance 1 exiting!
Experiment Complete

**Comment by tadatitam** [comment]
I'm sorry you're having difficulty running AdFisher. Let me try and troubleshoot. 

Currently, AdFisher requires Firefox to run experiments. Do you have Firefox installed?

**Comment by triplexacies** [comment]
firefox -v
Mozilla Firefox 42.0

**Comment by tadatitam** [comment]
Ok, great. It's really difficult to figure out what is wrong. Are you running the experiments by ssh-ing onto a server? Does it have access to an external display? 

If not, set headless to True in the make_browser function.

**Comment by triplexacies** [comment]
I didn't realize I was working in the prices when I tested the demo_exp.py. As the headless was defaulted to true on refactored. This solved the problem, however back on refactored when I run test.gender.jobs.py it still generates

WebDriverException: Message: Can't load the profile. Profile Dir: %s If you speified a log_file in the FirefoxBinary constructor, check it for details.


In prices, is there a specific working file I should test?

**Comment by triplexacies** [comment]
To confirm demo_exp.py is working on both versions.

**Comment by triplexacies** [comment]
This solved the problem, I forgot I changed it to true when working on xvfb failed to start. However  when I run test.gender.jobs.py it still generates

WebDriverException: Message: Can't load the profile. Profile Dir: %s If you speified a log_file in the FirefoxBinary constructor, check it for details.


Is there a specific working file I should test?
To confirm demo_exp.py is working.

**Comment by tadatitam** [comment]
I am not surprised that gender.jobs is not running - Google no longer allows access to the Ad Settings page when not logged in, so functions like opt_in and set_gender will no longer work. So, if you comment out those two lines from the control and experimental treatment definitions, the remaining experiment should run. (But that wont be a very interesting experiment since both the treatments will be identical).

I would suggest running test.substance.py after removing the opt_in() lines from both the control and experimental treatments for a full experiment. 

But I do find the 'WebDriverException' error you encounter pretty odd.
